In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../Airlinedataset.csv")

df.head()

,days_to_departure,seats_remaining,historical_demand,competitor_price,booking_velocity,is_weekend,flight_capacity,occupied_seats,occupancy_rate,ticket_price
0,39,38,51,8030,30,1,150,112,0.746667,10783
1,52,96,30,8232,1,1,180,84,0.466667,8341
2,29,99,64,7250,11,0,180,81,0.450000,9062
3,15,76,52,6657,7,0,220,144,0.654545,9802
4,43,43,60,8183,17,1,150,107,0.713333,10643

In [3]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 1000
Columns: 10

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   days_to_departure  1000 non-null   int64
 1   seats_remaining    1000 non-null   int64
 2   historical_demand  1000 non-null   int64
 3   competitor_price   1000 non-null   int64
 4   booking_velocity   1000 non-null   int64
 5   is_weekend         1000 non-null   int64
 6   flight_capacity    1000 non-null   int64
 7   occupied_seats     1000 non-null   int64
 8   occupancy_rate     1000 non-null   float64
 9   ticket_price       1000 non-null   int64
dtypes: float64(1), int64(9)
memory usage: 78.3 KB

In [5]:
df.isnull().sum()

days_to_departure    0
seats_remaining      0
historical_demand    0
competitor_price     0
booking_velocity     0
is_weekend           0
flight_capacity      0
occupied_seats       0
occupancy_rate       0
ticket_price         0
dtype: int64

In [6]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
days_to_departure,1000.0,31.200000,17.372905,1.0,17.000000,32.000000,47.000000,60.000000
seats_remaining,1000.0,89.296000,50.931625,5.0,44.000000,87.000000,134.000000,180.000000
historical_demand,1000.0,58.461000,23.412232,20.0,39.000000,57.000000,79.000000,100.000000
competitor_price,1000.0,6264.393000,1553.431407,3506.0,4977.000000,6169.500000,7508.250000,8999.000000
booking_velocity,1000.0,15.985000,8.771757,1.0,8.000000,17.000000,24.000000,30.000000
is_weekend,1000.0,0.511000,0.500129,0.0,0.000000,1.000000,1.000000,1.000000
flight_capacity,1000.0,185.000000,28.681399,150.0,150.000000,180.000000,220.000000,220.000000
occupied_seats,1000.0,95.704000,57.963058,-30.0,52.000000,97.000000,139.000000,215.000000
occupancy_rate,1000.0,0.506448,0.294960,-0.2,0.281818,0.536364,0.755556,0.977273
ticket_price,1000.0,9454.540000,1316.616664,5449.0,8535.000000,9504.500000,10450.750000,13346.000000

In [8]:
for column in df.columns:
    print(f"\n{column}")
    print("Unique values:", df[column].nunique())

days_to_departure
Unique values: 60

seats_remaining
Unique values: 176

historical_demand
Unique values: 81

competitor_price
Unique values: 916

booking_velocity
Unique values: 30

is_weekend
Unique values: 2

flight_capacity
Unique values: 3

occupied_seats
Unique values: 232

occupancy_rate
Unique values: 412

ticket_price
Unique values: 905